[tool.poetry]
name = "{{ cookiecutter.project_name }}"
version = "0.1.0"
description = "A FastAPI project"
authors = ["Me"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
